# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'research.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(535, 411)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setSpacing(0)
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.labelFrameMove = QtWidgets.QLabel(self.centralwidget)
        self.labelFrameMove.setAutoFillBackground(False)
        self.labelFrameMove.setStyleSheet("background-color: rgba(255, 0, 255, 56);\n"
"color: rgb(255, 255, 255);")
        self.labelFrameMove.setFrameShape(QtWidgets.QFrame.Box)
        self.labelFrameMove.setObjectName("labelFrameMove")
        self.horizontalLayout_2.addWidget(self.labelFrameMove)
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setStyleSheet("color: rgb(255, 255, 255);")
        self.label_2.setObjectName("label_2")
        self.horizontalLayout_2.addWidget(self.label_2)
        self.sliderOpacity = QtWidgets.QSlider(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.sliderOpacity.sizePolicy().hasHeightForWidth())
        self.sliderOpacity.setSizePolicy(sizePolicy)
        self.sliderOpacity.setStyleSheet("background: transparent;")
        self.sliderOpacity.setProperty("value", 50)
        self.sliderOpacity.setOrientation(QtCore.Qt.Horizontal)
        self.sliderOpacity.setObjectName("sliderOpacity")
        self.horizontalLayout_2.addWidget(self.sliderOpacity)
        spacerItem = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_2.addItem(spacerItem)
        self.buttonExit = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.buttonExit.sizePolicy().hasHeightForWidth())
        self.buttonExit.setSizePolicy(sizePolicy)
        self.buttonExit.setMaximumSize(QtCore.QSize(30, 16777215))
        self.buttonExit.setStyleSheet("background-color: rgba(255, 0, 255, 56);\n"
"color: rgb(255, 255, 255);")
        self.buttonExit.setObjectName("buttonExit")
        self.horizontalLayout_2.addWidget(self.buttonExit)
        self.verticalLayout.addLayout(self.horizontalLayout_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setSpacing(0)
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setMinimumSize(QtCore.QSize(1, 1))
        self.label.setStyleSheet("background: transparent;")
        self.label.setFrameShape(QtWidgets.QFrame.NoFrame)
        self.label.setText("")
        self.label.setScaledContents(False)
        self.label.setObjectName("label")
        self.horizontalLayout.addWidget(self.label)
        spacerItem1 = QtWidgets.QSpacerItem(0, 0, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.horizontalLayout.addItem(spacerItem1)
        self.verticalLayout.addLayout(self.horizontalLayout)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setSpacing(0)
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        spacerItem2 = QtWidgets.QSpacerItem(40, 20, QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Minimum)
        self.horizontalLayout_5.addItem(spacerItem2)
        self.labelFrameResize = QtWidgets.QLabel(self.centralwidget)
        self.labelFrameResize.setAutoFillBackground(False)
        self.labelFrameResize.setStyleSheet("background-color: rgba(255, 0, 255, 56);\n"
"color: rgb(255, 255, 255);")
        self.labelFrameResize.setFrameShape(QtWidgets.QFrame.Box)
        self.labelFrameResize.setAlignment(QtCore.Qt.AlignRight|QtCore.Qt.AlignTrailing|QtCore.Qt.AlignVCenter)
        self.labelFrameResize.setObjectName("labelFrameResize")
        self.horizontalLayout_5.addWidget(self.labelFrameResize)
        self.verticalLayout.addLayout(self.horizontalLayout_5)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.labelFrameMove.setText(_translate("MainWindow", "Move"))
        self.label_2.setText(_translate("MainWindow", "Opacity"))
        self.buttonExit.setText(_translate("MainWindow", "Exit"))
        self.labelFrameResize.setText(_translate("MainWindow", "Size"))



if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
